spring.application.name=adoAI

# Configuracao da API do Gemini (segura via variavel de ambiente)
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent

# Banco H2
spring.jpa.show-sql=true
spring.h2.console.enabled=true